- name: loops
  hosts: server
  #connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello, {{ item }}"
    loop:
    - suresh
    - ramesh
    - joseph
    - raheem
