- name: install packages
  hosts: node
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - {name: 'mysql' , state: 'absent'}
    - {name: 'nginx' , state: 'present'}
    - {name: 'zip' , state: 'absent'}